#!/usr/bin/with-contenv sh

until pg_isready; do
  echo "Waiting for postgres to come up..."
  sleep 1
done

# Create database if it does not exist
psql -U postgres -lqt | cut -d \| -f 1 | grep -qw $POSTGRES_DB
if [ $? -ne 0 ]; then
  createdb -U postgres -O postgres $POSTGRES_DB
fi

cd /app

# Database migrations
node node_modules/sequelize-cli/bin/sequelize db:migrate

echo "Starting unms..."
exec node --optimize_for_size --max_old_space_size=1000 --gc_interval=120 index.js
