#!/usr/bin/with-contenv sh

mkdir -p /config/postgres /run/postgresql
chown postgres:postgres /config/postgres /run/postgresql
chmod 0700 /config/postgres

if [ -e /config/postgres/postgresql.conf ]; then
  echo "Database already configured"
else
  s6-setuidgid postgres initdb
fi
