#!/usr/bin/with-contenv bash

HOME_DIR=""
UNMS_DIR="${HOME_DIR}/app"
DATA_DIR="${UNMS_DIR}/data"
PUBLIC_DIR="${UNMS_DIR}/public"

set -e
dirs=(
  ${UNMS_DIR}/supportinfo
  ${DATA_DIR}/cert
  ${DATA_DIR}/images
  ${DATA_DIR}/firmwares
  ${DATA_DIR}/logs
  ${DATA_DIR}/config-backups
  ${DATA_DIR}/unms-backups
  ${DATA_DIR}/import
  ${DATA_DIR}/update
)

links=(
  "${PUBLIC_DIR}/site-images:${DATA_DIR}/images"
  "${PUBLIC_DIR}/firmwares:${DATA_DIR}/firmwares"
)

echo "Creating directories and setting permissions"

# setpwd.sh is only accessible by root
chown root ${UNMS_DIR}/setpwd.sh
chmod 700 ${UNMS_DIR}/setpwd.sh

# create dir for Letsencrypt challenge
# until we figure out how to move it under home dir (UNMS-1073)
leDir="${UNMS_DIR}/letsencrypt"
mkdir -p "${leDir}"
chown -R abc "${leDir}"
chmod -R u+rwX,g-rwx,o-rwx "${leDir}"

# create cert dir symlink to data dir if not mounted by install script
if [ ! -d "${UNMS_DIR}/cert" ] && [ ! -L "${UNMS_DIR}/cert" ]; then
  echo "Linking ${UNMS_DIR}/cert -> ${DATA_DIR}/cert"
  ln -s "${DATA_DIR}/cert" "${UNMS_DIR}/cert"
fi

# if cert dir was mounted by install script, delete cert under data dir
if [ ! -L "${UNMS_DIR}/cert" ]; then
  rm -rf "${DATA_DIR}/cert"
fi

for dir in "${dirs[@]}"; do
  echo "creating ${dir}"
  if [ ! -L "${dir}" ]; then mkdir -p "${dir}"; fi
  chown -R abc:abc "${dir}"
  chmod -R u+rwX,g-rwx,o-rwx "${dir}"
done

for i in "${links[@]}"; do
  IFS=':' read -ra LINK <<< "${i}"
  linkFrom=${LINK[0]}
  linkTo=${LINK[1]}
  if [ -L "${linkFrom}" ] || [ -d "${linkFrom}" ]; then rm -rf "${linkFrom}"; fi
  echo "Linking ${linkFrom} -> ${linkTo}"
  ln -s "${linkTo}" "${linkFrom}"
done
